### ISSUE TITLE
Post Method: Simple dictionary post request.

### ISSUE THREAD

**Issue by dvetal** [industrydive/dive_sailthru_client#3]
Define a function within DiveSailthruClient called 'post_data' or something similar.  The goal of the function is to provide the user with a simple way to update records in sailthru via the API.

**Input Arguments:**  
'key': The name of the key field as a string.  Should accept only exactly what the existing API accepts as a key.
'data': A dictionary that includes the key as a key in the dictionary plus includes one or more other field names as keys of data that we want to update.

An example of a call might be 

post_data('key' = 'sid', data = {'sid': '123SDfefg', 'job_title': 'Strap Hanger', 'alt_email':'bob@gmail.com'}

In this case this call would update the 'alt_email' and job_title of the subscriber.

**Output**
No output expected other than some indication that the call was successful and the data was updated.

**Comment by elidickinson** [comment]
You can do this with `save_user()` https://getstarted.sailthru.com/developers/api/user/#UpdateUser
